# Service definitions for the WhatsApp Integration

send_message:
  name: Send message
  description: Send a WhatsApp message to a specific number.
  fields:
    number:
      name: Number
      description: The phone number to send the message to (with country code, e.g., 551199999999). Required if group is not specified.
      required: false
      selector:
        text:
    group:
      name: Group Name
      description: The exact name of the group to send the message to. Required if number is not specified.
      required: false
      selector:
        text:
    message:
      name: Message
      description: The content of the message.
      required: true
      selector:
        text:


send_broadcast:
  name: Send Broadcast
  description: Send a message to multiple targets (numbers or groups).
  fields:
    message:
      name: Message
      description: The content of the message.
      required: true
      selector:
        text:
    targets:
      name: Targets
      description: A list of phone numbers or group names.
      required: true
      selector:
        object:
